/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/annuaire`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ressources`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/demarche`; params?: Router.UnknownInputParams; } | { pathname: `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/profil/informations`; params?: Router.UnknownInputParams; } | { pathname: `/demarche/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/annuaire`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ressources`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/demarche`; params?: Router.UnknownOutputParams; } | { pathname: `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/profil/informations`; params?: Router.UnknownOutputParams; } | { pathname: `/demarche/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/annuaire${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ressources${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/demarche${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `/profil/informations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/annuaire`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ressources`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/demarche`; params?: Router.UnknownInputParams; } | { pathname: `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/profil/informations`; params?: Router.UnknownInputParams; } | `/demarche/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/demarche/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
