/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/planificateur`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/annuaire` | `/annuaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ressources` | `/ressources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil/informations` | `/profil/informations`; params?: Router.UnknownInputParams; } | { pathname: `/demarche`; params?: Router.UnknownInputParams; } | { pathname: `/demarche/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/planificateur`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/annuaire` | `/annuaire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ressources` | `/ressources`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil/informations` | `/profil/informations`; params?: Router.UnknownOutputParams; } | { pathname: `/demarche`; params?: Router.UnknownOutputParams; } | { pathname: `/demarche/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/notifications${`?${string}` | `#${string}` | ''}` | `/planificateur${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/annuaire${`?${string}` | `#${string}` | ''}` | `/annuaire${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ressources${`?${string}` | `#${string}` | ''}` | `/ressources${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil/informations${`?${string}` | `#${string}` | ''}` | `/profil/informations${`?${string}` | `#${string}` | ''}` | `/demarche${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/planificateur`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/annuaire` | `/annuaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ressources` | `/ressources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil/informations` | `/profil/informations`; params?: Router.UnknownInputParams; } | { pathname: `/demarche`; params?: Router.UnknownInputParams; } | `/demarche/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/demarche/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
